"""Memory writer — constructs MemoryChunk dicts with embedding vectors.

Each chunk gets an embedding generated by the EmbeddingService before
being written to DB, enabling semantic vector search via pgvector.
"""
from app.core.logging import get_logger
from app.models.enums import MemoryStatus, MemoryType
from app.services.embedding_service import EmbeddingService

logger = get_logger(__name__)


class MemoryWriter:
    """Builds MemoryChunk dicts with auto-generated embeddings."""

    def __init__(self) -> None:
        self.embedding_service = EmbeddingService()

    def _attach_embedding(self, chunk: dict) -> dict:
        """Generate and attach embedding vector to a memory chunk.
        Gracefully skips if embedding service is unavailable."""
        text = chunk.get("content", "")
        if not text:
            return chunk
        vec = self.embedding_service.embed_text(text)
        if vec:
            chunk["embedding"] = vec
            logger.info("memory_writer.embedding_attached", extra={"type": chunk.get("memoryType"), "dim": len(vec)})
        else:
            logger.warning("memory_writer.embedding_skipped", extra={"type": chunk.get("memoryType")})
        return chunk

    def _attach_embeddings_batch(self, chunks: list[dict]) -> list[dict]:
        """Batch-generate embeddings for multiple chunks at once."""
        if not chunks:
            return chunks
        texts = [c.get("content", "") for c in chunks]
        logger.info("memory_writer.batch_embedding", extra={"count": len(texts), "total_chars": sum(len(t) for t in texts)})
        vectors = self.embedding_service.embed_batch(texts)
        attached = 0
        for chunk, vec in zip(chunks, vectors):
            if vec:
                chunk["embedding"] = vec
                attached += 1
        logger.info("memory_writer.batch_embedding.done", extra={"total": len(chunks), "attached": attached})
        return chunks

    def write_summary_memory(self, project_id: str, chapter: dict, summary: str) -> dict:
        """Build a chapter summary MemoryChunk with embedding."""
        chunk = {
            "projectId": project_id,
            "sourceId": chapter["id"],
            "sourceType": "chapter",
            "memoryType": MemoryType.SUMMARY.value,
            "content": summary,
            "summary": summary,
            "tags": ["chapter", "summary"],
            "status": MemoryStatus.AUTO.value,
            "importanceScore": 90,
            "freshnessScore": 95,
            "recencyScore": 95,
            "sourceTrace": {
                "projectId": project_id,
                "chapterId": chapter["id"],
                "chapterNo": chapter.get("chapterNo"),
                "kind": "chapter_summary",
            },
        }
        return self._attach_embedding(chunk)

    def write_event_memories(self, project_id: str, chapter: dict, events: list[dict]) -> list[dict]:
        """Build event MemoryChunks with embeddings."""
        chunks = [
            {
                "projectId": project_id,
                "sourceType": "chapter",
                "sourceId": chapter["id"],
                "memoryType": MemoryType.EVENT.value,
                "content": event["description"],
                "summary": event["title"],
                "tags": ["chapter", "event", event.get("eventType", "event")],
                "status": MemoryStatus.AUTO.value,
                "importanceScore": 75,
                "freshnessScore": 85,
                "recencyScore": 85,
                "metadata": {
                    "eventType": event.get("eventType"),
                    "participants": event.get("participants", []),
                },
                "sourceTrace": {
                    "projectId": project_id,
                    "chapterId": chapter["id"],
                    "chapterNo": chapter.get("chapterNo"),
                    "kind": "event",
                },
            }
            for event in events
        ]
        return self._attach_embeddings_batch(chunks)

    def write_character_state_memories(self, project_id: str, chapter: dict, states: list[dict]) -> list[dict]:
        """Build character state MemoryChunks with embeddings."""
        chunks = [
            {
                "projectId": project_id,
                "sourceType": "chapter",
                "sourceId": chapter["id"],
                "memoryType": MemoryType.CHARACTER_STATE.value,
                "content": f"{state['character']}：{state['stateValue']}",
                "summary": state.get("summary") or f"{state['character']}状态更新",
                "tags": ["chapter", "character_state", state["character"]],
                "status": MemoryStatus.PENDING_REVIEW.value,
                "importanceScore": 70,
                "freshnessScore": 80,
                "recencyScore": 80,
                "metadata": {
                    "character": state["character"],
                    "stateType": state.get("stateType", "state"),
                },
                "sourceTrace": {
                    "projectId": project_id,
                    "chapterId": chapter["id"],
                    "chapterNo": chapter.get("chapterNo"),
                    "kind": "character_state",
                },
            }
            for state in states
        ]
        return self._attach_embeddings_batch(chunks)

    def write_foreshadow_memories(self, project_id: str, chapter: dict, foreshadows: list[dict]) -> list[dict]:
        """Build foreshadow MemoryChunks with embeddings."""
        chunks = [
            {
                "projectId": project_id,
                "sourceType": "chapter",
                "sourceId": chapter["id"],
                "memoryType": MemoryType.FORESHADOW.value,
                "content": foreshadow.get("detail") or foreshadow["title"],
                "summary": foreshadow["title"],
                "tags": ["chapter", "foreshadow"],
                "status": MemoryStatus.PENDING_REVIEW.value,
                "importanceScore": 65,
                "freshnessScore": 75,
                "recencyScore": 75,
                "metadata": {
                    "foreshadowStatus": foreshadow.get("status", "planned"),
                },
                "sourceTrace": {
                    "projectId": project_id,
                    "chapterId": chapter["id"],
                    "chapterNo": chapter.get("chapterNo"),
                    "kind": "foreshadow",
                },
            }
            for foreshadow in foreshadows
        ]
        return self._attach_embeddings_batch(chunks)
