export const GUIDED_SINGLE_CHAPTER_REFINEMENT_SCHEMA = '{"chapters":[{"chapterNo":1,"volumeNo":1,"title":"章节标题（保留原核心意图）","objective":"本章目标（具体可检验）","conflict":"核心冲突（写清阻力来源和方式）","outline":"Markdown，必须以 ## 本章执行卡 开头，并包含表层目标/隐藏情绪/核心冲突/入场状态/场景链/行动链/物证/线索/对话潜台词/人物变化/不可逆后果/离场状态/下一章交接","craftBrief":{"visibleGoal":"表层目标","hiddenEmotion":"隐藏情绪","coreConflict":"核心冲突","mainlineTask":"本章主线任务","subplotTasks":["支线任务"],"actionBeats":["行动链节点"],"sceneBeats":[{"sceneArcId":"跨章场景ID","scenePart":"1/3","continuesFromChapterNo":null,"continuesToChapterNo":2,"location":"具体地点","participants":["角色名"],"localGoal":"本场局部目标","visibleAction":"可被镜头拍到的动作","obstacle":"阻力来源和方式","turningPoint":"反转或新信息","partResult":"场景段结果","sensoryAnchor":"感官锚点"}],"concreteClues":[{"name":"物证或线索","sensoryDetail":"感官细节","laterUse":"后续用途"}],"dialogueSubtext":"对话潜台词","characterShift":"人物变化","irreversibleConsequence":"不可逆后果","progressTypes":["info"],"entryState":"接住上一章压力","exitState":"本章结束状态","openLoops":["未解决问题"],"closedLoops":["阶段性解决问题"],"handoffToNextChapter":"下一章接续动作和压力","continuityState":{"characterPositions":["角色位置"],"activeThreats":["仍在生效的威胁"],"ownedClues":["已持有线索"],"relationshipChanges":["关系变化"],"nextImmediatePressure":"下一章最紧迫压力"}}}]}';

export const GUIDED_STEP_JSON_SCHEMAS = {
  guided_setup: '{"genre":"小说类型","theme":"核心主题","tone":"故事基调","logline":"一句话概述","synopsis":"故事简介"}',
  guided_style: '{"pov":"人称视角","tense":"时态","proseStyle":"文风描述","pacing":"节奏描述"}',
  guided_characters: '{"characters":[{"name":"角色名","roleType":"protagonist/antagonist/supporting/competitor","personalityCore":"性格核心","motivation":"核心动机","backstory":"背景故事"}]}',
  guided_outline: '{"outline":"完整的故事总纲大纲"}',
  guided_volume: '{"volumes":[{"volumeNo":1,"title":"有文学性的卷名","synopsis":"Markdown结构，必须含## 全书主线阶段/## 本卷主线/## 本卷戏剧问题/## 卷内支线/## 支线交叉点/## 卷末交接等段落","objective":"本卷核心目标(具体可检验)","narrativePlan":{"globalMainlineStage":"全书主线阶段","volumeMainline":"本卷主线","dramaticQuestion":"本卷戏剧问题","startState":"开局状态","endState":"结尾状态","mainlineMilestones":["关键节点"],"subStoryLines":[{"name":"支线名","type":"mystery","function":"叙事作用","startState":"起点","progress":"推进方式","endState":"阶段结果","relatedCharacters":["角色名"],"chapterNodes":[1]}],"foreshadowPlan":["伏笔分配"],"endingHook":"卷末钩子","handoffToNextVolume":"卷末交接"}}]}',
  guided_chapter: '{"chapters":[{"chapterNo":1,"volumeNo":1,"title":"章节标题","objective":"本章目标","conflict":"核心冲突","outline":"章节大纲，必须含主线任务、支线任务、3-5个具体场景段、阶段结果和下一章交接","craftBrief":{"visibleGoal":"表层目标","hiddenEmotion":"隐藏情绪","coreConflict":"核心冲突","mainlineTask":"本章主线任务","subplotTasks":["支线任务"],"actionBeats":["行动链节点"],"sceneBeats":[{"sceneArcId":"跨章场景ID","scenePart":"1/3","continuesFromChapterNo":null,"continuesToChapterNo":2,"location":"具体地点","participants":["角色名"],"localGoal":"本场局部目标","visibleAction":"可被镜头拍到的动作","obstacle":"阻力来源和方式","turningPoint":"反转或新信息","partResult":"场景段结果","sensoryAnchor":"感官锚点"}],"concreteClues":[{"name":"物证或线索","sensoryDetail":"感官细节","laterUse":"后续用途"}],"dialogueSubtext":"对话潜台词","characterShift":"人物变化","irreversibleConsequence":"不可逆后果","progressTypes":["info"],"entryState":"接住上一章压力","exitState":"本章结束状态","openLoops":["未解决问题"],"closedLoops":["阶段性解决问题"],"handoffToNextChapter":"下一章接续动作和压力","continuityState":{"characterPositions":["角色位置"],"activeThreats":["仍在生效的威胁"],"ownedClues":["已持有线索"],"relationshipChanges":["关系变化"],"nextImmediatePressure":"下一章最紧迫压力"}}}],"supportingCharacters":[{"name":"角色名","roleType":"supporting","personalityCore":"性格核心(含内在矛盾)","motivation":"具体动机","firstAppearChapter":1}]}',
  guided_foreshadow: '{"foreshadowTracks":[{"title":"伏笔标题","detail":"伏笔内容详细描述","scope":"arc/volume/chapter","technique":"伏笔手法类型","plantChapter":"埋设时机","revealChapter":"揭开时机","involvedCharacters":"涉及角色","payoff":"揭开后的影响"}]}',
} as const;

export type GuidedStepSchemaKey = keyof typeof GUIDED_STEP_JSON_SCHEMAS;

export function getGuidedStepJsonSchema(stepKey: string): string | undefined {
  return Object.prototype.hasOwnProperty.call(GUIDED_STEP_JSON_SCHEMAS, stepKey)
    ? GUIDED_STEP_JSON_SCHEMAS[stepKey as GuidedStepSchemaKey]
    : undefined;
}
